import React from 'react';
export const warehouseDetails = () => <div>warehouse distinct</div>;
export const warehouse_detail_0 = (p:any)=> <div>warehouse 0 cold storage</div>;
export const warehouse_detail_1 = (p:any)=> <div>warehouse 1 kegs</div>;
export const warehouse_detail_2 = (p:any)=> <div>warehouse 2 pallets</div>;
export const warehouse_detail_3 = (p:any)=> <div>warehouse 3 FIFO</div>;
export const warehouse_detail_4 = (p:any)=> <div>warehouse 4 cold storage</div>;
export const warehouse_detail_5 = (p:any)=> <div>warehouse 5 kegs</div>;
export const warehouse_detail_6 = (p:any)=> <div>warehouse 6 pallets</div>;
export const warehouse_detail_7 = (p:any)=> <div>warehouse 7 FIFO</div>;
export const warehouse_detail_8 = (p:any)=> <div>warehouse 8 cold storage</div>;
export const warehouse_detail_9 = (p:any)=> <div>warehouse 9 kegs</div>;
export const warehouse_detail_10 = (p:any)=> <div>warehouse 10 pallets</div>;
export const warehouse_detail_11 = (p:any)=> <div>warehouse 11 FIFO</div>;
export const warehouse_detail_12 = (p:any)=> <div>warehouse 12 cold storage</div>;
export const warehouse_detail_13 = (p:any)=> <div>warehouse 13 kegs</div>;
export const warehouse_detail_14 = (p:any)=> <div>warehouse 14 pallets</div>;
export const warehouse_detail_15 = (p:any)=> <div>warehouse 15 FIFO</div>;
export const warehouse_detail_16 = (p:any)=> <div>warehouse 16 cold storage</div>;
export const warehouse_detail_17 = (p:any)=> <div>warehouse 17 kegs</div>;
export const warehouse_detail_18 = (p:any)=> <div>warehouse 18 pallets</div>;
export const warehouse_detail_19 = (p:any)=> <div>warehouse 19 FIFO</div>;