import React from 'react';
export const frontendDetails = () => <div>frontend distinct</div>;
export const frontend_detail_0 = (p:any)=> <div>frontend 0 brew dashboard</div>;
export const frontend_detail_1 = (p:any)=> <div>frontend 1 tank farm</div>;
export const frontend_detail_2 = (p:any)=> <div>frontend 2 inventory</div>;
export const frontend_detail_3 = (p:any)=> <div>frontend 3 brew dashboard</div>;
export const frontend_detail_4 = (p:any)=> <div>frontend 4 tank farm</div>;
export const frontend_detail_5 = (p:any)=> <div>frontend 5 inventory</div>;
export const frontend_detail_6 = (p:any)=> <div>frontend 6 brew dashboard</div>;
export const frontend_detail_7 = (p:any)=> <div>frontend 7 tank farm</div>;
export const frontend_detail_8 = (p:any)=> <div>frontend 8 inventory</div>;
export const frontend_detail_9 = (p:any)=> <div>frontend 9 brew dashboard</div>;
export const frontend_detail_10 = (p:any)=> <div>frontend 10 tank farm</div>;
export const frontend_detail_11 = (p:any)=> <div>frontend 11 inventory</div>;
export const frontend_detail_12 = (p:any)=> <div>frontend 12 brew dashboard</div>;
export const frontend_detail_13 = (p:any)=> <div>frontend 13 tank farm</div>;
export const frontend_detail_14 = (p:any)=> <div>frontend 14 inventory</div>;
export const frontend_detail_15 = (p:any)=> <div>frontend 15 brew dashboard</div>;
export const frontend_detail_16 = (p:any)=> <div>frontend 16 tank farm</div>;
export const frontend_detail_17 = (p:any)=> <div>frontend 17 inventory</div>;
export const frontend_detail_18 = (p:any)=> <div>frontend 18 brew dashboard</div>;
export const frontend_detail_19 = (p:any)=> <div>frontend 19 tank farm</div>;