import React from 'react';
export const batchesDetails = () => <div>batches distinct</div>;
export const batches_detail_0 = (p:any)=> <div>batches 0 lot tracking</div>;
export const batches_detail_1 = (p:any)=> <div>batches 1 brew day</div>;
export const batches_detail_2 = (p:any)=> <div>batches 2 fermentation</div>;
export const batches_detail_3 = (p:any)=> <div>batches 3 genealogy</div>;
export const batches_detail_4 = (p:any)=> <div>batches 4 lot tracking</div>;
export const batches_detail_5 = (p:any)=> <div>batches 5 brew day</div>;
export const batches_detail_6 = (p:any)=> <div>batches 6 fermentation</div>;
export const batches_detail_7 = (p:any)=> <div>batches 7 genealogy</div>;
export const batches_detail_8 = (p:any)=> <div>batches 8 lot tracking</div>;
export const batches_detail_9 = (p:any)=> <div>batches 9 brew day</div>;
export const batches_detail_10 = (p:any)=> <div>batches 10 fermentation</div>;
export const batches_detail_11 = (p:any)=> <div>batches 11 genealogy</div>;
export const batches_detail_12 = (p:any)=> <div>batches 12 lot tracking</div>;
export const batches_detail_13 = (p:any)=> <div>batches 13 brew day</div>;
export const batches_detail_14 = (p:any)=> <div>batches 14 fermentation</div>;
export const batches_detail_15 = (p:any)=> <div>batches 15 genealogy</div>;
export const batches_detail_16 = (p:any)=> <div>batches 16 lot tracking</div>;
export const batches_detail_17 = (p:any)=> <div>batches 17 brew day</div>;
export const batches_detail_18 = (p:any)=> <div>batches 18 fermentation</div>;
export const batches_detail_19 = (p:any)=> <div>batches 19 genealogy</div>;