import React from 'react';
export const salesDetails = () => <div>sales distinct</div>;
export const sales_detail_0 = (p:any)=> <div>sales 0 orders</div>;
export const sales_detail_1 = (p:any)=> <div>sales 1 invoices</div>;
export const sales_detail_2 = (p:any)=> <div>sales 2 taproom POS</div>;
export const sales_detail_3 = (p:any)=> <div>sales 3 keg deposits</div>;
export const sales_detail_4 = (p:any)=> <div>sales 4 orders</div>;
export const sales_detail_5 = (p:any)=> <div>sales 5 invoices</div>;
export const sales_detail_6 = (p:any)=> <div>sales 6 taproom POS</div>;
export const sales_detail_7 = (p:any)=> <div>sales 7 keg deposits</div>;
export const sales_detail_8 = (p:any)=> <div>sales 8 orders</div>;
export const sales_detail_9 = (p:any)=> <div>sales 9 invoices</div>;
export const sales_detail_10 = (p:any)=> <div>sales 10 taproom POS</div>;
export const sales_detail_11 = (p:any)=> <div>sales 11 keg deposits</div>;
export const sales_detail_12 = (p:any)=> <div>sales 12 orders</div>;
export const sales_detail_13 = (p:any)=> <div>sales 13 invoices</div>;
export const sales_detail_14 = (p:any)=> <div>sales 14 taproom POS</div>;
export const sales_detail_15 = (p:any)=> <div>sales 15 keg deposits</div>;
export const sales_detail_16 = (p:any)=> <div>sales 16 orders</div>;
export const sales_detail_17 = (p:any)=> <div>sales 17 invoices</div>;
export const sales_detail_18 = (p:any)=> <div>sales 18 taproom POS</div>;
export const sales_detail_19 = (p:any)=> <div>sales 19 keg deposits</div>;