import React from 'react';
export const recipesDetails = () => <div>recipes distinct</div>;
export const recipes_detail_0 = (p:any)=> <div>recipes 0 style</div>;
export const recipes_detail_1 = (p:any)=> <div>recipes 1 BJCP</div>;
export const recipes_detail_2 = (p:any)=> <div>recipes 2 grain bill</div>;
export const recipes_detail_3 = (p:any)=> <div>recipes 3 hop schedule</div>;
export const recipes_detail_4 = (p:any)=> <div>recipes 4 style</div>;
export const recipes_detail_5 = (p:any)=> <div>recipes 5 BJCP</div>;
export const recipes_detail_6 = (p:any)=> <div>recipes 6 grain bill</div>;
export const recipes_detail_7 = (p:any)=> <div>recipes 7 hop schedule</div>;
export const recipes_detail_8 = (p:any)=> <div>recipes 8 style</div>;
export const recipes_detail_9 = (p:any)=> <div>recipes 9 BJCP</div>;
export const recipes_detail_10 = (p:any)=> <div>recipes 10 grain bill</div>;
export const recipes_detail_11 = (p:any)=> <div>recipes 11 hop schedule</div>;
export const recipes_detail_12 = (p:any)=> <div>recipes 12 style</div>;
export const recipes_detail_13 = (p:any)=> <div>recipes 13 BJCP</div>;
export const recipes_detail_14 = (p:any)=> <div>recipes 14 grain bill</div>;
export const recipes_detail_15 = (p:any)=> <div>recipes 15 hop schedule</div>;
export const recipes_detail_16 = (p:any)=> <div>recipes 16 style</div>;
export const recipes_detail_17 = (p:any)=> <div>recipes 17 BJCP</div>;
export const recipes_detail_18 = (p:any)=> <div>recipes 18 grain bill</div>;
export const recipes_detail_19 = (p:any)=> <div>recipes 19 hop schedule</div>;